language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t dylanskelly/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dylanskelly/docker-react npm run test